from FireWall.enums import Porta

class Mapa:
    MOTORDIREITO = Porta.PD
    MOTORESQUERDO = Porta.PA

    SENSORINFERIORESQUERDO = Porta.P1
    SENSORINFERIORDIREIRO = Porta.P4
    
    SENSORSUPERIORESQUERDO = Porta.P2
    SENSORSUPERIORDIREITO = Porta.P3
    
    GIROSCOPIO = Porta.P3